export default {
    THEME_SELECTION_START: 'THEME_SELECTION_START',
    THEME_SELECTION_SUCCESS:'THEME_SELECTION_SUCCESS',
    THEME_SELECTION_ERROR: 'THEME_SELECTION_SUCCESS',
    THEME_SELECTION_END: 'THEME_SELECTION_END'
}